#-#-#-#-#-#-#-#-#-#-#-#-#-#
# $Id: Makefile,v 1.4 2006/01/12 22:32:38 mmr Exp $
# <mmr@b1n.org> 2004/02
#

# Prog
PROG=	cube.exe
SRC=	cube.c

# Apps
CC=		gcc


# Flags
LDFLAGS=-lglut32 -lglu32 -lopengl32 -mwindows

all:
	$(CC) -o $(PROG) $(SRC) $(LDFLAGS)
