#-#-#-#-#-#-#-#-#-#-#-#-#-#
# $Id: Makefile,v 1.4 2006/01/12 22:32:38 mmr Exp $
# <mmr@b1n.org> 2004/02
#

# Prog
PROG=	cube
SRCS=	cube.c
OBJS=	cube.o

# Apps
CC=		gcc


# Flags
CFLAGS=
LDFLAGS=-framework OpenGL -framework GLUT

all: $(PROG)

$(SRCS):
	$(GET) $@

clean:
	-rm -f *.o *.core $(PROG)
